(() => {
const KEY="h_management_cockpit_v2",cfg=window.H_CONFIG,$=s=>document.querySelector(s);
let state=load(),view="dashboard",editing={type:null,id:null};
function clone(o){return JSON.parse(JSON.stringify(o))}
function load(){try{const r=localStorage.getItem(KEY);if(r)return {...clone(window.H_DEFAULT_DATA),...JSON.parse(r)}}catch(e){}return clone(window.H_DEFAULT_DATA)}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function uid(){return Date.now().toString(36)+Math.random().toString(36).slice(2,7)}
function n(v){const x=Number(v);return Number.isFinite(x)?x:0}
function money(v){return n(v).toLocaleString("pt-BR",{style:"currency",currency:"BRL",maximumFractionDigits:0})}
function dateBR(v){if(!v)return"—";const [y,m,d]=v.split("-");return d&&m&&y?`${d}/${m}/${y}`:v}
function idx(s){return Math.max(0,cfg.stages.findIndex(x=>x.id===s))}
function stageLabel(s){const x=cfg.stages.find(a=>a.id===s);return x?`${x.id} • ${x.label}`:"—"}
function badge(v){const c=v==="Ativa"?"green":v==="Em espera"?"orange":v==="Perdida"?"red":v==="Encerrada"?"blue":"gray";return `<span class="badge ${c}"><span class="dot"></span>${v||"Sem status"}</span>`}
function contribution(r){return n(r.revenue)-n(r.consultantCost)-n(r.taxes)}
function margin(r){return n(r.revenue)?contribution(r)/n(r.revenue)*100:0}
function weighted(r){return n(r.opportunityValue)*(n(r.probability)/100)}
const titles={dashboard:["Cockpit","Visão executiva da jornada completa, do Radar à Expansão."],journey:["Oportunidades & Projetos","Um único registro percorre S0 → S7."],cash:["Caixa","Planejamento financeiro aberto, sem metas fixas."],meeting:["Modo Reunião","Roteiro executivo com pipeline, projetos, riscos, expansão e ações."]};
function setView(v){view=v;document.querySelectorAll(".nav-item").forEach(b=>b.classList.toggle("active",b.dataset.view===v));$("#viewTitle").textContent=titles[v][0];$("#viewSubtitle").textContent=titles[v][1];$("#primaryAction").textContent=v==="cash"?"+ Novo período":v==="meeting"?"+ Nova ação":"+ Nova oportunidade";render()}
function render(){({dashboard:renderDashboard,journey:renderJourney,cash:renderCash,meeting:renderMeeting}[view])()}
function kpi(a,b,c){return `<div class="kpi-card"><div class="kpi-label">${a}</div><div class="kpi-value">${b}</div><div class="kpi-foot">${c}</div></div>`}
function renderDashboard(){
 const active=state.records.filter(r=>["Ativa","Em espera"].includes(r.status||"Ativa")),commercial=active.filter(r=>idx(r.stage)<=4),backlog=active.filter(r=>r.stage==="S5"),delivery=active.filter(r=>r.stage==="S6");
 const stages=cfg.stages.map(st=>{const arr=active.filter(r=>r.stage===st.id);let val=0;arr.forEach(r=>val+=idx(st.id)<=4?n(r.opportunityValue):n(r.revenue||r.opportunityValue));return `<div class="stage-card"><div class="stage-code">${st.id}</div><div class="stage-name">${st.label}</div><div class="stage-meta">${arr.length} registro(s)<br>${money(val)}</div></div>`}).join("");
 const alerts=[];active.forEach(r=>{if(idx(r.stage)<=4&&!r.nextStep)alerts.push(`${r.client||"Conta"} — sem próximo passo.`);if(r.stage==="S6"&&!r.expansionHypothesis)alerts.push(`${r.client||"Cliente"} — sem hipótese de expansão.`)});
 $("#content").innerHTML=`<div class="kpi-grid">${kpi("Pipeline bruto",money(commercial.reduce((s,r)=>s+n(r.opportunityValue),0)),commercial.length+" oportunidades")}${kpi("Pipeline ponderado",money(commercial.reduce((s,r)=>s+weighted(r),0)),"Valor x probabilidade")}${kpi("Backlog contratado",money(backlog.reduce((s,r)=>s+n(r.revenue||r.opportunityValue),0)),backlog.length+" registro(s)")}${kpi("Contribuição Delivery",money(delivery.reduce((s,r)=>s+contribution(r),0)),delivery.length+" projeto(s)")}</div>
 <div class="panel" style="margin-bottom:16px"><div class="section-head"><div><h3>Esteira H!</h3><div class="panel-sub">S0 Radar → S7 Expand. Um único registro atravessa toda a jornada.</div></div></div><div class="stage-strip">${stages}</div></div>
 <div class="grid-2"><div class="panel"><h3>Projetos em Delivery</h3><div class="panel-sub">Economics dos registros em S6.</div>${delivery.length?`<div class="cards-list">${delivery.map(r=>`<div class="list-card"><h4>${r.client||"Cliente"} — ${r.opportunity||"Projeto"}</h4><p>Lead: ${r.projectLead||"—"} • Execução: ${n(r.progress)}% • Margem: ${margin(r).toFixed(1).replace(".",",")}%</p><div class="progress"><span style="width:${Math.min(100,Math.max(0,n(r.progress)))}%"></span></div><p>Contribuição: <strong>${money(contribution(r))}</strong></p></div>`).join("")}</div>`:`<div class="empty">Nenhum projeto em S6.</div>`}</div><div class="panel"><h3>Alertas</h3><div class="panel-sub">Itens para reunião.</div>${alerts.length?`<div class="alert-list">${alerts.map(a=>`<div class="alert">${a}</div>`).join("")}</div>`:`<div class="empty">Nenhum alerta.</div>`}</div></div>`;
}
function renderJourney(){
 const sf=$("#stageFilterValue")?.value||"",stf=$("#statusFilterValue")?.value||"",q=($("#searchValue")?.value||"").toLowerCase();
 const rows=state.records.filter(r=>(!sf||r.stage===sf)&&(!stf||r.status===stf)&&(!q||[r.client,r.opportunity,r.owner,r.sponsor].some(v=>(v||"").toLowerCase().includes(q))));
 $("#content").innerHTML=`<div class="panel"><div class="section-head"><div><h3>Jornada única</h3><div class="panel-sub">${rows.length} registro(s). A etapa atual define os campos da fase.</div></div><button class="primary" id="addRecordBtn">+ Nova oportunidade</button></div><div class="filterbar"><select id="stageFilterValue"><option value="">Todas as etapas</option>${cfg.stages.map(s=>`<option value="${s.id}" ${sf===s.id?"selected":""}>${s.id} • ${s.label}</option>`).join("")}</select><select id="statusFilterValue"><option value="">Todos os status</option>${cfg.statuses.map(s=>`<option ${stf===s?"selected":""}>${s}</option>`).join("")}</select><input id="searchValue" value="${q}" placeholder="Buscar cliente, projeto, owner..."></div><div class="table-wrap"><table><thead><tr><th>Cliente</th><th>Oportunidade / Projeto</th><th>Etapa</th><th>Status</th><th>Valor</th><th>Owner</th><th>Sponsor</th><th>Próximo passo</th><th>Data</th><th>Ações</th></tr></thead><tbody>${rows.length?rows.map(r=>`<tr><td>${r.client||"—"}</td><td>${r.opportunity||"—"}</td><td>${stageLabel(r.stage)}</td><td>${badge(r.status||"Ativa")}</td><td>${money(idx(r.stage)<=4?r.opportunityValue:(r.revenue||r.opportunityValue))}</td><td>${r.owner||"—"}</td><td>${r.sponsor||"—"}</td><td>${r.nextStep||"—"}</td><td>${dateBR(r.nextStepDate)}</td><td><div class="inline-actions"><button class="mini-btn edit" data-id="${r.id}">Abrir / Editar</button><button class="mini-btn danger del" data-id="${r.id}">Excluir</button></div></td></tr>`).join(""):`<tr><td colspan="10" class="empty">Nenhum registro.</td></tr>`}</tbody></table></div></div>`;
 $("#addRecordBtn").addEventListener("click",()=>openRecord());["stageFilterValue","statusFilterValue"].forEach(i=>$("#"+i).addEventListener("change",renderJourney));$("#searchValue").addEventListener("input",renderJourney);document.querySelectorAll(".edit").forEach(b=>b.addEventListener("click",()=>openRecord(b.dataset.id)));document.querySelectorAll(".del").forEach(b=>b.addEventListener("click",()=>{if(confirm("Excluir este registro?")){state.records=state.records.filter(r=>r.id!==b.dataset.id);save();renderJourney()}}))
}
function renderCash(){let acc=0;const cards=state.cash.map(r=>{const g=n(r.actualRevenue)-n(r.consultantCost)-n(r.taxes)-n(r.fixedCosts)-n(r.withdrawals)+n(r.other);acc+=g;return `<div class="cash-card"><h4>${r.month||"Período"}</h4><dl><dt>Receita prevista</dt><dd>${money(r.forecastRevenue)}</dd><dt>Receita realizada</dt><dd>${money(r.actualRevenue)}</dd><dt>Consultores</dt><dd>${money(r.consultantCost)}</dd><dt>Impostos</dt><dd>${money(r.taxes)}</dd><dt>Custos fixos</dt><dd>${money(r.fixedCosts)}</dd><dt>Retiradas</dt><dd>${money(r.withdrawals)}</dd><dt>Outros</dt><dd>${money(r.other)}</dd><dt class="cash-total">Caixa gerado</dt><dd class="cash-total">${money(g)}</dd><dt>Acumulado</dt><dd>${money(acc)}</dd></dl><div class="inline-actions" style="margin-top:12px"><button class="mini-btn cashEdit" data-id="${r.id}">Editar</button><button class="mini-btn danger cashDel" data-id="${r.id}">Excluir</button></div></div>`}).join("");$("#content").innerHTML=`<div class="panel"><div class="section-head"><div><h3>Planejamento de Caixa</h3><div class="panel-sub">Todos os campos abertos.</div></div><button class="primary" id="addCash">+ Novo período</button></div><div class="cash-grid">${cards||'<div class="empty">Nenhum período.</div>'}</div></div>`;$("#addCash").addEventListener("click",()=>openCash());document.querySelectorAll(".cashEdit").forEach(b=>b.addEventListener("click",()=>openCash(b.dataset.id)));document.querySelectorAll(".cashDel").forEach(b=>b.addEventListener("click",()=>{if(confirm("Excluir período?")){state.cash=state.cash.filter(r=>r.id!==b.dataset.id);save();renderCash()}}))}
function step(n,t,p){return `<div class="meeting-step"><div class="meeting-num">${n}</div><div><h4>${t}</h4><p>${p}</p></div></div>`}
function renderMeeting(){const a=state.records.filter(r=>["Ativa","Em espera"].includes(r.status||"Ativa"));$("#content").innerHTML=`<div class="grid-2"><div class="panel"><div class="section-head"><div><h3>Agenda Executiva</h3><div class="panel-sub">Roteiro padrão para reunião interna.</div></div><button class="primary" id="addAction">+ Ação / decisão</button></div><div class="meeting-flow">${step(1,"Caixa e recebimentos",state.cash.length+" período(s) cadastrado(s).")}${step(2,"Pipeline comercial",a.filter(r=>idx(r.stage)<=4).length+" oportunidade(s).")}${step(3,"Commit / fechamentos",a.filter(r=>r.stage==="S4").length+" oportunidade(s) em S4.")}${step(4,"Backlog",a.filter(r=>r.stage==="S5").length+" registro(s) em S5.")}${step(5,"Delivery",a.filter(r=>r.stage==="S6").length+" projeto(s) em S6.")}${step(6,"Economics e margem","Revisar contribuição, custos e impostos.")}${step(7,"Capacidade / pessoas","Revisar leads e especialistas.")}${step(8,"Expansão",a.filter(r=>r.stage==="S7").length+" registro(s) em S7.")}${step(9,"Decisões pendentes",state.meetingActions.filter(x=>(x.status||"").toLowerCase()!=="concluído").length+" ação(ões) em aberto.")}${step(10,"Ações da semana","Fechar responsável e prazo.")}</div></div><div class="panel"><h3>Action Log</h3><div class="panel-sub">Decisões e compromissos.</div>${state.meetingActions.length?`<div class="table-wrap"><table style="min-width:650px"><thead><tr><th>Data</th><th>Tema</th><th>Responsável</th><th>Prazo</th><th>Status</th><th>Ações</th></tr></thead><tbody>${state.meetingActions.map(x=>`<tr><td>${dateBR(x.date)}</td><td>${x.topic||"—"}</td><td>${x.owner||"—"}</td><td>${dateBR(x.dueDate)}</td><td>${x.status||"—"}</td><td><button class="mini-btn actEdit" data-id="${x.id}">Editar</button></td></tr>`).join("")}</tbody></table></div>`:'<div class="empty">Nenhuma ação.</div>'}</div></div>`;$("#addAction").addEventListener("click",()=>openAction());document.querySelectorAll(".actEdit").forEach(b=>b.addEventListener("click",()=>openAction(b.dataset.id)))}
function field(name,label,type,val=""){return `<div class="field"><label>${label}</label><input name="${name}" type="${type}" value="${String(val||"").replace(/"/g,"&quot;")}" ${type==="number"?'step="any"':''}></div>`}
function textarea(name,label,val=""){return `<div class="field full"><label>${label}</label><textarea name="${name}">${val||""}</textarea></div>`}
function select(name,label,opts,val=""){return `<div class="field"><label>${label}</label><select name="${name}"><option value="">Selecione...</option>${opts.map(([v,l])=>`<option value="${v}" ${v===val?"selected":""}>${l}</option>`).join("")}</select></div>`}
function journey(stage){const i=idx(stage||"S0");return `<div class="journey-line">${cfg.stages.map((s,j)=>`<span class="journey-pill ${j<i?"done":j===i?"current":""}">${s.id} ${s.label}</span>${j<7?'<span class="journey-arrow">›</span>':""}`).join("")}</div>`}
function openRecord(id=null){editing={type:"record",id};const r=id?state.records.find(x=>x.id===id):{stage:"S0",status:"Ativa"};$("#modalTitle").textContent=id?(r.client||"Registro")+" — "+stageLabel(r.stage):"Nova oportunidade";$("#formBody").innerHTML=recordForm(r);$("#modalBackdrop").classList.remove("hidden");bindStage()}
function recordForm(r){const i=idx(r.stage||"S0"),sec=(m,t,d,f)=>i>=m?`<section class="form-section"><h3>${t}</h3><p>${d}</p><div class="form-grid">${f.join("")}</div></section>`:"";return `<div class="stage-helper"><strong>Jornada atual</strong>${journey(r.stage)}<span>Ao avançar a etapa, novos campos aparecem e os anteriores permanecem salvos.</span></div><section class="form-section"><h3>Dados principais</h3><p>Acompanham o registro durante toda a jornada.</p><div class="form-grid">${field("client","Cliente / Conta","text",r.client)}${field("opportunity","Oportunidade / Projeto","text",r.opportunity)}${select("stage","Etapa atual",cfg.stages.map(s=>[s.id,`${s.id} • ${s.label}`]),r.stage||"S0")}${select("status","Status",cfg.statuses.map(s=>[s,s]),r.status||"Ativa")}${field("owner","Account Owner","text",r.owner)}${field("sponsor","Sponsor / Influenciador","text",r.sponsor)}${field("nextStep","Próximo passo","text",r.nextStep)}${field("nextStepDate","Data próximo passo","date",r.nextStepDate)}${textarea("generalNotes","Observações gerais",r.generalNotes)}</div></section>
${sec(0,"S0 | Radar & Relacionamento","Hipótese inicial e origem.",[textarea("painHypothesis","Hipótese de dor / agenda executiva",r.painHypothesis),field("source","Origem / indicação / advisor","text",r.source)])}
${sec(1,"S1 | Oportunidade Qualificada","Sponsor, dor, timing e fit.",[textarea("qualifiedPain","Dor confirmada",r.qualifiedPain),field("urgency","Urgência / timing","text",r.urgency),field("buyingCapacity","Capacidade / processo de contratação","text",r.buyingCapacity),textarea("qualificationNotes","Qualificação / Go-No-Go",r.qualificationNotes)])}
${sec(2,"S2 | Discovery & Solução","Problema, valor e abordagem.",[textarea("problemDefinition","Problema / contexto",r.problemDefinition),textarea("expectedValue","Resultado esperado / valor",r.expectedValue),textarea("solutionHypothesis","Hipótese de solução H!",r.solutionHypothesis),field("decisionProcess","Decisores / processo decisório","text",r.decisionProcess)])}
${sec(3,"S3 | Proposta","Economics e escopo.",[field("opportunityValue","Valor da proposta","number",r.opportunityValue),field("probability","Probabilidade (%)","number",r.probability),field("closeForecast","Previsão de fechamento","date",r.closeForecast),textarea("scope","Escopo / entregáveis",r.scope),field("expectedMargin","Margem prevista (%)","number",r.expectedMargin)])}
${sec(4,"S4 | Commit","Negociação final.",[field("negotiationStatus","Status da negociação","text",r.negotiationStatus),textarea("legalProcurement","Compras / jurídico / pendências",r.legalProcurement),field("expectedStart","Data provável de início","date",r.expectedStart),textarea("commercialConditions","Condições / concessões",r.commercialConditions)])}
${sec(5,"S5 | Backlog","Mobilização e handoff.",[field("revenue","Receita contratada","number",r.revenue),field("startDate","Data de início","date",r.startDate),field("endDate","Data de término","date",r.endDate),field("projectLead","Project Lead","text",r.projectLead),textarea("team","Time / capacidade",r.team),textarea("billingPlan","Plano de faturamento",r.billingPlan)])}
${sec(6,"S6 | Delivery","Execução e economics.",[field("consultantCost","Custo consultores","number",r.consultantCost),field("taxes","Impostos","number",r.taxes),field("progress","% executado","number",r.progress),textarea("risksDecisions","Riscos / decisões",r.risksDecisions),field("nextDecision","Próxima decisão","text",r.nextDecision),textarea("expansionHypothesis","Hipótese de expansão",r.expansionHypothesis)])}
${sec(7,"S7 | Expand","Próxima wave / continuidade.",[textarea("expansionOpportunity","Próxima oportunidade",r.expansionOpportunity),field("expansionType","Tipo de expansão","text",r.expansionType),field("expansionValue","Valor potencial","number",r.expansionValue),field("expansionApproachDate","Momento de abordagem","date",r.expansionApproachDate),textarea("expansionPlan","Plano de abordagem",r.expansionPlan)])}` }
function bindStage(){const s=document.querySelector('[name="stage"]');if(s)s.addEventListener("change",()=>{const fd=new FormData($("#recordForm")),p={};for(const[k,v]of fd.entries())p[k]=v;const old=editing.id?state.records.find(x=>x.id===editing.id):{};$("#formBody").innerHTML=recordForm({...old,...p,stage:s.value});bindStage()})}
function openCash(id=null){editing={type:"cash",id};const r=id?state.cash.find(x=>x.id===id):{};$("#modalTitle").textContent=id?"Editar período":"Novo período";$("#formBody").innerHTML=`<section class="form-section"><div class="form-grid">${field("month","Mês / período","month",r.month)}${field("forecastRevenue","Receita prevista","number",r.forecastRevenue)}${field("actualRevenue","Receita realizada","number",r.actualRevenue)}${field("consultantCost","Custo consultores","number",r.consultantCost)}${field("taxes","Impostos","number",r.taxes)}${field("fixedCosts","Custos fixos","number",r.fixedCosts)}${field("withdrawals","Retiradas","number",r.withdrawals)}${field("other","Outros (+/-)","number",r.other)}${textarea("notes","Observações",r.notes)}</div></section>`;$("#modalBackdrop").classList.remove("hidden")}
function openAction(id=null){editing={type:"action",id};const r=id?state.meetingActions.find(x=>x.id===id):{};$("#modalTitle").textContent=id?"Editar ação":"Nova ação";$("#formBody").innerHTML=`<section class="form-section"><div class="form-grid">${field("date","Data da reunião","date",r.date)}${field("topic","Tema / decisão","text",r.topic)}${field("owner","Responsável","text",r.owner)}${field("dueDate","Prazo","date",r.dueDate)}${field("status","Status","text",r.status)}${textarea("notes","Notas",r.notes)}</div></section>`;$("#modalBackdrop").classList.remove("hidden")}
function close(){editing={type:null,id:null};$("#modalBackdrop").classList.add("hidden")}
$("#recordForm").addEventListener("submit",e=>{e.preventDefault();const fd=new FormData(e.currentTarget),obj={};for(const[k,v]of fd.entries())obj[k]=v;if(editing.type==="record"){if(editing.id){const i=state.records.findIndex(r=>r.id===editing.id);state.records[i]={...state.records[i],...obj}}else state.records.push({id:uid(),...obj})}else if(editing.type==="cash"){if(editing.id){const i=state.cash.findIndex(r=>r.id===editing.id);state.cash[i]={...state.cash[i],...obj}}else state.cash.push({id:uid(),...obj})}else{if(editing.id){const i=state.meetingActions.findIndex(r=>r.id===editing.id);state.meetingActions[i]={...state.meetingActions[i],...obj}}else state.meetingActions.push({id:uid(),...obj})}save();close();render()});
$("#nav").addEventListener("click",e=>{const b=e.target.closest("[data-view]");if(b)setView(b.dataset.view)});$("#primaryAction").addEventListener("click",()=>view==="cash"?openCash():view==="meeting"?openAction():openRecord());$("#closeModalBtn").addEventListener("click",close);$("#cancelModalBtn").addEventListener("click",close);$("#exportBtn").addEventListener("click",()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="H_Cockpit_Backup.json";a.click();URL.revokeObjectURL(a.href)});$("#importInput").addEventListener("change",async e=>{const f=e.target.files[0];if(!f)return;try{state={...clone(window.H_DEFAULT_DATA),...JSON.parse(await f.text())};save();render();alert("Backup importado.")}catch(err){alert("Arquivo inválido.")}});$("#resetBtn").addEventListener("click",()=>{if(confirm("Limpar todos os dados?")){state=clone(window.H_DEFAULT_DATA);save();setView("dashboard")}});setView("dashboard");
})();